### ISSUE TITLE
Refactor Product API

### ISSUE THREAD

**Issue by queyenth** [codedropcc/fastmag#7]
Right now it creates Simple and Bundle product in different way.
For simple, it creates Fastmag\Product\Simple product and assign data to it, but for bundle it do it using factory.

I think, API should has no createSimple / createBundle / createConfigurable.  
It should has only create method, which get's data and create product.

/cc @codedropcc/developers

**Comment by queyenth** [comment]
@Dunkon 
Do we need that Fastmag\Product\Api? I mean, why not do like in magento?
Just Fastmag\Product\Factory::create($data) and afterwards just save, and that's all?
Do we really need one more class for it?

**Comment by Dunkon** [comment]
@queyenth 
I think we can remove that file from the past. It is unnecessary at this moment. Isn't it?

**Comment by queyenth** [comment]
@Dunkon will take a look tomorrow.
